/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeptotest_zeptoroids_ZrSurfaceView */

#ifndef _Included_org_zeptotest_zeptoroids_ZrSurfaceView
#define _Included_org_zeptotest_zeptoroids_ZrSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeptotest_zeptoroids_ZrSurfaceView
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_ZrSurfaceView_nativePause
  (JNIEnv *, jclass);

/*
 * Class:     org_zeptotest_zeptoroids_ZrSurfaceView
 * Method:    nativeResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_ZrSurfaceView_nativeResume
  (JNIEnv *, jclass);

/*
 * Class:     org_zeptotest_zeptoroids_ZrSurfaceView
 * Method:    nativeTogglePauseResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_ZrSurfaceView_nativeTogglePauseResume
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
