/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeptotest_zeptoroids_ZrRenderer */

#ifndef _Included_org_zeptotest_zeptoroids_ZrRenderer
#define _Included_org_zeptotest_zeptoroids_ZrRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeptotest_zeptoroids_ZrRenderer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_ZrRenderer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     org_zeptotest_zeptoroids_ZrRenderer
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_ZrRenderer_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zeptotest_zeptoroids_ZrRenderer
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_ZrRenderer_nativeRender
  (JNIEnv *, jclass);

/*
 * Class:     org_zeptotest_zeptoroids_ZrRenderer
 * Method:    nativeDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_ZrRenderer_nativeDone
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
