/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeptotest_zeptoroids_MainActivity */

#ifndef _Included_org_zeptotest_zeptoroids_MainActivity
#define _Included_org_zeptotest_zeptoroids_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeptotest_zeptoroids_MainActivity
 * Method:    nativePointerDown
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_MainActivity_nativePointerDown
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_zeptotest_zeptoroids_MainActivity
 * Method:    nativePointerUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_MainActivity_nativePointerUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeptotest_zeptoroids_MainActivity
 * Method:    nativePointerDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeptotest_zeptoroids_MainActivity_nativePointerDone
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
